# The URL the site will be built for
base_url = "https://blog.gokuls.in"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The site title and description; used in feeds by default.
title = "bahdotsh"
description = "Rust • FOSS • Programming"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "radion"

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"

[extra]
# Put all your custom variables here
author = "bahdotsh"
theme = "dark"
enable_search = true
toc = true
radion_menu = [
    { name = "Home", url = "$BASE_URL" },
    { name = "Categories", url = "$BASE_URL/categories" },
    { name = "Source", url = "https://github.com/bahdotsh/blog" },
    { name = "GitHub", url = "https://github.com/bahdotsh" },
    { name = "RSS", url = "$BASE_URL/rss.xml" },
    { name = "About", url = "https://gokuls.in" },
]
codeblock = true
latex = true
# Giscus comment support
comments = true
giscus_repo = "bahdotsh/blog"
giscus_repo_id = "R_kgDOOJbE2g"
giscus_data_category_id = "DIC_kwDOOJbE2s4CoGkM"
radion_title = "bahdotsh's blog"
